food2go/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

HANDLER400 = TemplateView.as_view(template_name='errors/400.html')
HANDLER403 = TemplateView.as_view(template_name='errors/403.html') #'main.views.custom_403_view'
HANDLER404 = TemplateView.as_view(template_name='errors/404.html') #'main.views.custom_404_view'
HANDLER500 = TemplateView.as_view(template_name='errors/500.html') #'main.views.custom_500_view'

urlpatterns = [
    #path('', include('main.urls'), name='main'),
    path('pizza2go/', include('pizza2go.urls'), name='pizza2go'),
    path('admin/', admin.site.urls),
    #link structure imported from library
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

pizza2go/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'pizza2go'
urlpatterns = [
    path('', views.IndexView.as_view(), name='pizza2go-index'),
    path('add_to_cart/', views.add_to_cart, name='pizza2go-add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, \
        name='pizza2go-remove_from_cart'),
    path('create_order/', views.create_order, name='pizza2go-create_order'),
    path('complete_order/<int:order_id>/', views.complete_order, name='pizza2go-complete_order'),
    path('shopping_cart/', views.ShoppingCartView.as_view(), name='pizza2go-shopping_cart'),
    path('orders/', views.OrderView.as_view(), name='pizza2go-orders')
]

pizza2go/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class Topping(models.Model):
    name = models.CharField(unique=True, max_length=30)

    def __str__(self):
        return self.name

class Pizza(models.Model):
    name = models.CharField(unique=True, max_length=30)
    toppings = models.ManyToManyField(Topping)

    def __str__(self):
        return self.name

class PizzaSize(models.Model):
    name = models.CharField(max_length=30)
    diameter = models.IntegerField(validators=[
        MaxValueValidator(100),
        MinValueValidator(1)
    ])
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    #price = models.OneToOneField('PizzaPrice', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=4, decimal_places=2, validators=[
        MaxValueValidator(Decimal("99.99")),
        MinValueValidator(Decimal("0.01"))
    ])

    class Meta:
        ordering = ['diameter']
        unique_together = ('name', 'pizza',)

    def __str__(self):
        return self.name

class UserShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    pizza_size = models.ForeignKey(PizzaSize, on_delete=models.CASCADE)

    def __str__(self):
        username = self.user.username
        pizza_size_name = self.pizza_size.name
        pizza_name = self.pizza.name
        result = "%s: %s %s pizza" % (username, pizza_size_name, pizza_name)
        return result

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now_add=True)
    time_created = models.TimeField(auto_now_add=True)
    date_finished = models.DateField(null=True, blank=True)
    time_finished = models.TimeField(null=True, blank=True)
    active = models.BooleanField(default=True)

    def get_price(self):
        order_sum = Decimal(0.0)
        order_items = self.orderitem_set.all()
        for item in order_items:
            order_sum += item.pizza_size.price
        return order_sum

    def __str__(self):
        username = self.user.username
        active = "active" if self.active else "inactive"
        result = "%s's %s order, created at %s" % (username, active, self.date_created)
        return result

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    pizza_size = models.ForeignKey(PizzaSize, on_delete=models.CASCADE)

    def __str__(self):
        order = self.order
        pizza_size_name = self.pizza_size.name
        pizza_name = self.pizza.name
        result = "%s order - %s %s pizza" % (order, pizza_size_name, pizza_name)
        return result

pizza2go/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

pizza2go/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.models import User

from .models import Pizza, PizzaSize, UserShoppingCart, Order, OrderItem

class IndexView(generic.ListView):
    template_name = 'pizza2go/index.html'
    context_object_name = 'ordered_pizza_list'

    def get_queryset(self):
        """Return all pizzas alphabetically."""
        return Pizza.objects.order_by('name')

class ShoppingCartView(generic.ListView):
    template_name = 'pizza2go/shopping_cart.html'
    context_object_name = 'ordered_items_list'

    def get_queryset(self):
        """Returns all items alphabetically."""
        return UserShoppingCart.objects.filter(user=self.request.user).order_by("pizza")

def add_to_cart(request):
    size_id = request.POST.get('sizes')
    size = get_object_or_404(PizzaSize, pk=size_id)
    pizza = size.pizza
    user = request.user
    cart = UserShoppingCart(user=user, pizza=pizza, pizza_size=size)
    cart.save()
    return redirect('/pizza2go/')

def remove_from_cart(request, item_id):
    UserShoppingCart.objects.filter(id=item_id).delete()
    return redirect('/pizza2go/shopping_cart/')

def create_order(request):
    username = request.user
    shopping_cart_items = UserShoppingCart.objects.filter(user=username)
    #TODO: used to avoid ("back -> Create order" empty order). Check if possible to avoid it.
    if not shopping_cart_items:
        order = Order(user=username)
        order.save()
        for item in shopping_cart_items:
            order_item = OrderItem(order=order, pizza=item.pizza, pizza_size=item.pizza_size)
            order_item.save()
        shopping_cart_items.delete()
    return redirect('/pizza2go/orders/')

def complete_order(request, order_id):
    order = get_object_or_404(Order, order_id)
    now = datetime.now()
    order.date_finished = now
    order.time_finished = now
    order.active = False
    order.save()
    return redirect('/pizza2go/orders/')

class OrderView(generic.ListView):
    template_name = 'pizza2go/orders.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        """Returns all items by active."""
        return Order.objects.filter(user=self.request.user).order_by("-active")

pizza2go/templates/pizza2go/base_pizza2go.html
{% extends 'base.html' %}

{% block title %}Pizza2Go{% endblock %}

{% block content %}
  <h1><a href="{% url 'pizza2go:pizza2go-index' %}">Pizza2Go</a></h1>
  {% if user.is_authenticated %}
  <p><a href="{% url 'pizza2go:pizza2go-shopping_cart' %}">View Shopping Cart</a></p>
  <p><a href="{% url 'pizza2go:pizza2go-orders' %}">View Orders</a></p>
  {% endif %}

  {% block content_pizza2go %}
  {% endblock %}
{% endblock %}

pizza2go/templates/pizza2go/index.html
{% extends 'pizza2go/base_pizza2go.html' %}

{% block title %}Pizza2Go{% endblock %}

{% block content_pizza2go %}
    <h2>Pizzas</h2>
    {% if ordered_pizza_list %} 
      {% for pizza in ordered_pizza_list %}
        <h3>{{pizza.name}}</h3>
        <details>
          <summary>Toppings</summary>
          <ul>
            {% for topping in pizza.toppings.all %}
                <li>{{ topping.name }}</li>
            {% endfor %}
          </ul>
        </details>
        <form action="{% url 'pizza2go:pizza2go-add_to_cart' %}" method="post">
          {% csrf_token %}
          <div class="form-group" name="select-sizes">
              <label for="sizes">Sizes</label>
              <div class="row">
                <div class="form-group">
                  <select id="sizes" class="form-control" name="sizes" required>
                    <option value="">Choose...</option>
                    {% for size in pizza.pizzasize_set.all %}
                      <option value={{size.id}}>{{ size.name }}, {{size.diameter}} cm, {{size.price}} €</option>
                    {% endfor %}
                  </select>
                </div>
              </div> 
          </div>
          {% if user.is_authenticated %}
          <button class="btn btn-success" type="submit">Add to cart ({{ pizza.name }})</button>
          {% endif %}
        </form>
      {% endfor %}
    {% else %}
      <p>No pizzas are available.</p>
    {% endif %}
{% endblock %}

pizza2go/templates/pizza2go/orders.html
{% extends 'pizza2go/base_pizza2go.html' %}

{% block title %}Orders{% endblock %}

{% block content_pizza2go %}
    <div class="text-center">
        <h2>Orders</h2>
        {% if user.is_authenticated %}
            {% if order_list %} 
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Created</th>
                            <th scope="col">Finished</th>
                            <th scope="col">Price</th>
                            <th score="col">Details</th>
                            <th scope="col">Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_list %}
                            {% if order.active %}
                            <tr class="table-success">
                            {% else %}
                            <tr>
                            {% endif %}
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{order.date_created}} {{order.time_created}}</td>
                                <td>{% if not order.active %}
                                        {{order.date_finished}} {{order.time_finished}}
                                    {% endif %}
                                </td>
                                <td>{{order.get_price}}€</td>
                                <td>
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fas fa-ellipsis-h"></i>
                                    </button>
                                </td>
                                <td>
                                    {% if order.active %}
                                    <form action="{% url 'pizza2go:pizza2go-complete_order' order_id=order.id %}" method="post">
                                        {% csrf_token %}
                                        <button class="btn btn-success" type="submit">
                                            <i class="fas fa-shopping-cart"></i>
                                        </button>
                                    </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No orders are available.</p>
            {% endif %}
        {% else %}
            <p>Please login to see your orders.</p>
        {% endif %}
            <!--Place orders here, no buttons.
        All user orders (active and history)-->
    </div>
{% endblock %}

pizza2go/templates/pizza2go/shopping_cart.html
{% extends 'pizza2go/base_pizza2go.html' %}

{% block title %}Shopping Cart{% endblock %}

{% block content_pizza2go %}
    <h2>Shopping Cart</h2>
    {% if user.is_authenticated %}
        {% if ordered_items_list %}
            <ul>
                {% for item in ordered_items_list %}
                    <form action="{% url 'pizza2go:pizza2go-remove_from_cart' item_id=item.id %}" method="post">
                        {% csrf_token %}
                        <li>{{ item.pizza_size }} {{ item.pizza }}
                        <button class="btn btn-danger btn-sm" type="submit">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                {% endfor %}
            </ul>
            <form action="{% url 'pizza2go:pizza2go-create_order' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-lg btn-success" type="submit">Order</button>
            </form>
            <!--Here place button to pay up, another screen (purchase maybe)-->
        {% else %}
            <p>You have no items in shopping cart.</p>
        {% endif %}
    {% else %}
        <p>Please login to see your shopping cart.</p>
    {% endif %}
{% endblock %}